# netlify.toml

[build]
  # Ajuste conforme a pasta final do seu build
  publish = "dist"
  command = "npm run build"

# =======================================
# Regras de redirecionamento
# =======================================

# Voltar para tela de login se acessar páginas restritas
[[redirects]]
  from = "/pedidoextra"
  to = "/login"
  status = 302

[[redirects]]
  from = "/pedidomensal"
  to = "/login"
  status = 302

[[redirects]]
  from = "/calculadora"
  to = "/login"
  status = 302

[[redirects]]
  from = "/central-de-pedidos"
  to = "/login"
  status = 302

# Fallback para SPA (React, Vue, Angular, etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
