# netlify.toml

[build]
  # Publica a raiz do repositório
  publish = "."

# =======================================
# Redirecionamentos para forçar login
# =======================================

[[redirects]]
  from = "/pedidoextra"
  to = "/login"
  status = 302

[[redirects]]
  from = "/pedidomensal"
  to = "/login"
  status = 302

[[redirects]]
  from = "/calculadora"
  to = "/login"
  status = 302

[[redirects]]
  from = "/central-de-pedidos"
  to = "/login"
  status = 302

# =======================================
# Fallback SPA (React, Vue, Angular ou páginas internas)
# =======================================
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
